### ISSUE TITLE
Will be support PHP 8.3?

### ISSUE THREAD

**Issue by peerasan** [qxsch/WorkerPool#18]
found some error when run on php 8.3. I test with simple https://github.com/qxsch/WorkerPool#a-more-sophisticated-example
doesn't work.

```
PHP Fatal error:  Uncaught Error: Call to undefined function QXS\WorkerPool\sem_get() in /mnt/d/dev/Patrickz/test/vendor/qxsch/worker-pool/src/Semaphore.php:99
Stack trace:
#0 /mnt/d/dev/Patrickz/test/vendor/qxsch/worker-pool/src/WorkerPool.php(268): QXS\WorkerPool\Semaphore->create()
#1 /mnt/d/dev/Patrickz/test/test.php(59): QXS\WorkerPool\WorkerPool->create()
#2 {main}
  thrown in /mnt/d/dev/Patrickz/test/vendor/qxsch/worker-pool/src/Semaphore.php on line 99
PHP Fatal error:  Uncaught QXS\WorkerPool\SemaphoreException: Semaphore hasn't yet been created. in /mnt/d/dev/Patrickz/test/vendor/qxsch/worker-pool/src/Semaphore.php:186
Stack trace:
#0 /mnt/d/dev/Patrickz/test/vendor/qxsch/worker-pool/src/WorkerPool.php(443): QXS\WorkerPool\Semaphore->destroy()
#1 /mnt/d/dev/Patrickz/test/vendor/qxsch/worker-pool/src/WorkerPool.php(390): QXS\WorkerPool\WorkerPool->destroy()
#2 [internal function]: QXS\WorkerPool\WorkerPool->onShutDown()
#3 {main}
  thrown in /mnt/d/dev/Patrickz/test/vendor/qxsch/worker-pool/src/Semaphore.php on line 186
```

**PHP 8.3.0RC1 (cli) (built: Sep  2 2023 06:34:23) (NTS)**

**Comment by qxsch** [comment]
**Did you install the required modules?**

it seems, that sysvsem did not get installed. Read here on [sysvsem installation](https://www.php.net/manual/en/sem.installation.php).
In case you do not need semaphore (synchronization), **you can disable sempahore**:
```php
<?php

$wp=new \QXS\WorkerPool\WorkerPool();
$wp->setWorkerPoolSize(4)
   ->disableSemaphore()  // <--- this disables the semaphore support (you can still use it in the worker, but it will have no effect)
   ->create(new \QXS\WorkerPool\ClosureWorker(
                        /**
                          * @param mixed $input the input from the WorkerPool::run() Method
                          * @param \QXS\WorkerPool\Semaphore $semaphore the semaphore to synchronize calls accross all workers
                          * @param \ArrayObject $storage a persistent storage for the current child process
                          */
                        function($input, $semaphore, $storage) {
                                echo "[".getmypid()."]"." hi $input\n";
                                sleep(rand(1,3)); // this is the working load!
                                return $input; // return null here, in case you do not want to pass any data to the parent 
                        }
                )
);


for($i=0; $i<10; $i++) {
        $wp->run($i);
}

$wp->waitForAllWorkers(); // wait for all workers

foreach($wp as $val) {
        var_dump($val);  // dump the returned values
}
```

The following extensions are required:
 * [pcntl installation](https://www.php.net/manual/en/pcntl.installation.php)
 * [posix installation](https://www.php.net/manual/en/posix.setup.php)
 * [sysvsem installation](https://www.php.net/manual/en/sem.installation.php)
 * [sockets installation](https://www.php.net/manual/en/sockets.installation.php)
